varsion: 3

services:

 sender:
  build: ./ClickSender
  ports:
   - 3000:3000
  networks:
   - my-network

 worker:
  build: ./ClickWorker
  ports:
   - 3333:3333
  networks:
   - my-network

 db:
  image: mcr.microsoft.com/mssql/server:2022-latest
  environment: 
   - SA_PASSWORD=Password123
   - ACCEPT_EULA=Y
  ports:
   - 1433:1433
  networks:
   - my-network
  volume:
   - ./MssqlDB:/app/script
   - mssqlbackup:/var/opt/mssql
  command: sh /app/script/CreateTable.sh
   
 result:
  build: ./ClickResult
  ports:
   - 5000:5000
  networks:
   - my-network

networks:
 my-network