version: "3"

services:

 sender:
  build: ./ClickSender
  ports:
   - 3000:3000
  networks:
   - frontend

 worker:
  build: ./ClickWorker/ClickWorker
  environment: 
   - ASPNETCORE_URLS=http://+:3333
  ports:
   - 3333:3333
  networks:
   - frontend
   - backend

 db:
  build: ./MssqlDB
  environment: 
   - SA_PASSWORD=Password123
   - ACCEPT_EULA=Y
  networks:
   - backend
  ports:
   - 1433:1433
  volumes:
   - mssqlbackup:/var/opt/mssql
   - ./MssqlDB:/app/script
  command: sh /app/script/entrypoint.sh
   
 result:
  build: ./ClickResult
  ports:
   - 5000:5000
  networks:
   - frontend

volumes:
 mssqlbackup:

networks:
 frontend:
 backend: