version: "3"

services:

 sender:
  build: ./ClickSender
  ports:
   - 3000:3000
  networks:
   - frontend
  depends_on:
   - "worker"

 worker:
  build: ./ClickWorker/ClickWorker
  environment: 
   - ASPNETCORE_URLS=http://+:3333
  ports:
   - 3333:3333
  networks:
   - frontend
   - backend
  depends_on:
   - "db"

 db:
  build: ./MssqlDB
  networks:
   - backend
  volumes:
   - mssqlbackup:/var/opt/mssql
   
 result:
  build: ./ClickResult
  ports:
   - 5000:5000
  networks:
   - frontend
  depends_on:
   - "worker"

volumes:
 mssqlbackup:

networks:
 frontend:
 backend: