# FROM mcr.microsoft.com/mssql/server:2022-latest

# USER root


# ENV ACCEPT_EULA=Y
# ENV SA_PASSWORD=Password123
# ENV MSSQL_TCP_PORT=1433

# WORKDIR /app

# COPY . /app/script

# RUN chmod +x /app/script/entrypoint.sh

# RUN chmod +x /app/script/db-init.sh

# EXPOSE 1433

# CMD /bin/bash /app/script/entrypoint.sh